import React from 'react';
import { Document, Page, Text, View, StyleSheet, Font, Image } from '@react-pdf/renderer';
import { Panel } from '../types/panel';

Font.register({
  family: 'Inter',
  fonts: [
    { src: 'https://fonts.gstatic.com/s/inter/v12/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa1ZL7.ttf', fontWeight: 400 },
    { src: 'https://fonts.gstatic.com/s/inter/v12/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa25L7.ttf', fontWeight: 600 }
  ]
});

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Inter'
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 20,
    borderBottom: '1 solid #E5E7EB'
  },
  logo: {
    width: 120,
    height: 'auto'
  },
  title: {
    fontSize: 24,
    fontWeight: 600,
    color: '#111827'
  },
  subtitle: {
    fontSize: 14,
    color: '#6B7280',
    marginTop: 4
  },
  info: {
    marginTop: 20,
    padding: 15,
    backgroundColor: '#F3F4F6',
    borderRadius: 4
  },
  infoText: {
    fontSize: 10,
    color: '#4B5563',
    marginBottom: 4
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 8,
    color: '#9CA3AF',
    textAlign: 'center',
    paddingTop: 10,
    borderTop: '1 solid #E5E7EB'
  }
});

interface VisualizationPDFProps {
  panel: Panel;
  horizontalPanels: number;
  verticalPanels: number;
  logo?: string;
}

export function VisualizationPDF({ 
  panel, 
  horizontalPanels, 
  verticalPanels,
  logo 
}: VisualizationPDFProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          {logo && <Image src={logo} style={styles.logo} />}
          <View style={{ flex: 1, marginLeft: 20 }}>
            <Text style={styles.title}>LED Screen Layout</Text>
            <Text style={styles.subtitle}>
              {panel.name} • {horizontalPanels}×{verticalPanels} Configuration
            </Text>
          </View>
        </View>

        <View style={styles.info}>
          <Text style={styles.infoText}>
            Panel Model: {panel.name} ({panel.manufacturer})
          </Text>
          <Text style={styles.infoText}>
            Panel Size: {panel.width}×{panel.height}mm
          </Text>
          <Text style={styles.infoText}>
            Configuration: {horizontalPanels} panels wide × {verticalPanels} panels high
          </Text>
          <Text style={styles.infoText}>
            Total Size: {((horizontalPanels * panel.width) / 1000).toFixed(2)}×
            {((verticalPanels * panel.height) / 1000).toFixed(2)}m
          </Text>
        </View>

        <Text style={styles.footer}>
          Generated by AV Teknikk LED Panel Calculator • {new Date().toLocaleString()}
        </Text>
      </Page>
    </Document>
  );
}